WIP: Randomize the list of team members on the people page
reichlab/reichlab.github.io pull request #174
Opened 2024-01-29 22:24 UTC by bsweger

This is a low-friction way to shuffle the list of team members on [https://reichlab.io/people](https://reichlab.io/people)

The trade-off is that the order will change when the site is rebuilt but not when the page is refreshed.

If we want the lab's leaders to always be at the top, that should be do-able with a few more lines of code.

2024-01-29 22:35 UTC, bsweger commented
Here's what it looks like on localhost: 

![image](https://github.com/reichlab/reichlab.github.io/assets/540544/80862f8e-3179-4902-8ef4-b7344f18dd6a)

And after rebuilding the site:

![image](https://github.com/reichlab/reichlab.github.io/assets/540544/2699f318-d723-4ccb-a16d-47f27696bb0f)

2024-01-30 13:33 UTC, nickreich requested changes
Amazingly "low-friction"! Nice.

I think we should do this. My one comment is that maybe we should add a small piece of text just below the "People" header and before the "person cards" start that says something about the ordering, so visitors know what is going on. Something like "The ordering of lab members below is randomly shuffled once every day."

Also, this doesn't impact the ordering of alumni, right?

2024-01-30 14:25 UTC, bsweger commented
This change will also randomize the alumni list, because it randomizes everyone in team.yml. The distinction between current and former people is made downstream in people.html: https://github.com/reichlab/reichlab.github.io/blob/source/people.html#L57

If we don't want to randomize alumni, I can split the list earlier on and only shuffle the current team members.

Added some text--let me know if you'd like different wording:

![image](https://github.com/reichlab/reichlab.github.io/assets/540544/043be3be-7b1a-412e-b757-c49e78fff58b)

2024-01-30 15:54 UTC, nickreich commented
Maybe I'm being too finnicky here, but I actually do like the idea of keeping alumni list fixed (there is a clear linear timeline/ordering for them) and only randomizing current members.

2024-01-30 15:54 UTC, nickreich commented
All of this is making me wish we had netlify builds for site previews.

2024-01-30 21:25 UTC, nickreich requested changes
I vote for randomizing only current members, and leaving the alumni ordered, to enable easier temporal indexing of recent grads.

2024-01-31 18:52 UTC, bsweger commented
@nickreich just pushed a change that should limit randomization to current team members.

The diff is easier to grok if you disregard whitespaces: https://github.com/reichlab/reichlab.github.io/pull/174/files?w=1

Agree about a site preview (and will create an issue and let you prioritize accordingly). In the meantime, feel free to stop by for an in-person preview (I know, I know, not the best)

2024-01-31 19:37 UTC, nickreich approved these changes

2024-01-31 19:37 UTC, merged